import assert from 'node:assert/strict';
import { Pool } from 'pg';
import bcrypt from 'bcrypt';
const target = new URL(process.env.QA_DATABASE_URL || '');
if (!['localhost','127.0.0.1'].includes(target.hostname) || target.port !== '55473') throw new Error('Integration tests require the isolated local QA database');
process.env.DATABASE_URL=target.toString();
const db = new Pool({connectionString:process.env.DATABASE_URL});
await db.query(`CREATE TABLE users(id varchar PRIMARY KEY,password text NOT NULL); CREATE TABLE session(sid text PRIMARY KEY,sess json NOT NULL);
CREATE TABLE companies(id serial PRIMARY KEY,user_id varchar REFERENCES users(id),name text,summary text,gtm_motion text,icp_score integer,screenshot_url text,visual_analysis text,page_speed_data jsonb,site_profile jsonb,last_scraped timestamp,last_reanalyzed_at timestamp);
CREATE TABLE recommendations(id serial PRIMARY KEY,company_id integer,category text,title text,description text,impact text,effort text,status text,gtm_funnel text);
CREATE TABLE weekly_ideas(id serial PRIMARY KEY,company_id integer,title text NOT NULL,description text,type text);
CREATE TABLE channel_insights(id serial PRIMARY KEY,company_id integer,channel_id text,priority text,why_it_matters text,company_fit_summary text,hero_stat jsonb,top_kpis jsonb,strategic_pillars jsonb,quick_wins jsonb,resources jsonb,generation_status text,strategy_meta jsonb);`);
const {ensureAnalysisJobs,enqueueAnalysis,claimAnalysisJob,enqueueReanalysis,assertAnalysisLease,jobPool}=await import('../server/services/analysisJobs');
const {ensurePasswordRecovery,issueRecoveryToken,redeemRecoveryToken,validRecoveryInput,recoveryTokenHash}=await import('../server/services/passwordRecovery');
const {publishAnalysis}=await import('../server/services/analysisPublication');
await db.query(`INSERT INTO users VALUES('qa','old-hash'); INSERT INTO companies(user_id,name,summary) VALUES('qa','Original report','Original summary'); INSERT INTO session VALUES('old-session','{"userId":"qa"}');`);
await ensureAnalysisJobs();await ensurePasswordRecovery();
assert.equal(validRecoveryInput('bad','12345678'),false);
assert.equal(validRecoveryInput('a'.repeat(64),'é'.repeat(40)),false);
const token = await issueRecoveryToken('qa');assert.ok(token);
const stored=(await db.query('SELECT token_hash FROM password_recovery')).rows[0].token_hash;
assert.equal(stored,recoveryTokenHash(token));assert.notEqual(stored,token);
assert.equal(await issueRecoveryToken('qa'),null);
const redeemed=await Promise.all([redeemRecoveryToken(token,'isolated-fixture-password'),redeemRecoveryToken(token,'isolated-fixture-password')]);
assert.equal(redeemed.filter(Boolean).length,1);
assert.equal((await db.query('SELECT * FROM session')).rowCount,0);
assert.equal(await bcrypt.compare('isolated-fixture-password',(await db.query('SELECT password FROM users')).rows[0].password),true);
const expired=await issueRecoveryToken('qa');assert.ok(expired);
await db.query("UPDATE password_recovery SET expires_at=now()-interval '1 second'");
assert.equal(await redeemRecoveryToken(expired,'another-fixture-password'),false);
await enqueueAnalysis(1);await assert.rejects(()=>enqueueAnalysis(1));
const claims=await Promise.all([claimAnalysisJob(),claimAnalysisJob()]);assert.equal(claims.filter(Boolean).length,1);
const first=claims.find(Boolean)!;await assertAnalysisLease(1,first.token);
await db.query("UPDATE analysis_jobs SET lease_until=now()-interval '1 second'");
const second=await claimAnalysisJob();assert.ok(second);assert.notEqual(second.token,first.token);
await assert.rejects(()=>assertAnalysisLease(1,first.token));
const payload:any={core:{companyName:'New report',summary:'New summary',gtmMotion:'PLG',icpScore:80,recommendations:[{category:'SEO',title:'Task',description:'Do task',impact:'High',effort:'Low'}],weeklyIdeas:[{title:null,description:'Invalid fixture'}]},screenshotData:null,visualInsights:'',pageSpeedData:null,siteProfile:null,complete:[]};
await assert.rejects(()=>publishAnalysis(1,second.token,payload));
assert.equal((await db.query('SELECT name FROM companies')).rows[0].name,'Original report');
payload.core.weeklyIdeas=[];
await publishAnalysis(1,second.token,payload);
assert.equal((await db.query('SELECT name FROM companies')).rows[0].name,'New report');
assert.equal((await db.query('SELECT status FROM analysis_jobs')).rows[0].status,'completed');
const reruns=await Promise.allSettled([enqueueReanalysis(1,false,new Date(Date.now()-7*86400000)),enqueueReanalysis(1,false,new Date(Date.now()-7*86400000))]);
assert.equal(reruns.filter(item=>item.status==='fulfilled').length,1);
await db.query("UPDATE analysis_jobs SET status='failed'");
await enqueueReanalysis(1,false,new Date(Date.now()-7*86400000));
assert.equal((await db.query('SELECT status FROM analysis_jobs')).rows[0].status,'queued');
const {ensureScheduledRuns,runScheduledOnce}=await import('../server/services/scheduledRuns');
await ensureScheduledRuns();let batches=0;
await Promise.all([runScheduledOnce('fixture-week',async()=>{batches++;}),runScheduledOnce('fixture-week',async()=>{batches++;})]);assert.equal(batches,1);
console.log('PASS: hashed expiring single-use recovery, session revocation, concurrent job claim, worker recovery, stale-worker fencing, atomic rollback and publication');
await db.end();await jobPool.end();
