import { Link } from "wouter";
import { Zap, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageMeta } from "@/components/PageMeta";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <PageMeta
        title="Terms of Service - GTM Champion"
        description="Read the terms of service for using GTM Champion, the free AI-powered Go-To-Market strategy platform for B2B SaaS companies."
        path="/terms"
      />
      <nav className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50" role="navigation" aria-label="Main navigation">
        <div className="container mx-auto px-4 md:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-display font-bold text-lg" data-testid="link-home">
            <Zap className="h-5 w-5 fill-current text-primary" aria-hidden="true" />
            <span>GTM Champion</span>
          </Link>
          <Link href="/">
            <Button variant="ghost" size="sm" data-testid="button-back-home">
              <ArrowLeft className="h-4 w-4 mr-2" aria-hidden="true" />
              Back to Home
            </Button>
          </Link>
        </div>
      </nav>

      <main id="main-content" className="container mx-auto px-4 md:px-8 py-16 max-w-3xl">
        <h1 className="text-4xl font-display font-bold mb-2" data-testid="text-terms-heading">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

        <div className="prose prose-slate dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By accessing or using GTM Champion ("the Service"), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground">
              GTM Champion is an AI-powered Go-To-Market strategy platform for B2B SaaS companies. The Service 
              analyzes publicly available website content and generates personalized marketing strategy 
              recommendations across multiple channels. The Service includes AI-powered chat, content 
              generation tools, and weekly email strategy digests.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">3. User Accounts</h2>
            <ul className="list-disc pl-6 text-muted-foreground space-y-2">
              <li>You must provide a valid email address to create an account.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You may only analyze websites you own or have authorization to analyze.</li>
              <li>You must not create multiple accounts for the purpose of abusing the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">4. Acceptable Use</h2>
            <p className="text-muted-foreground mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-2">
              <li>Use the Service for any illegal or unauthorized purpose.</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble any part of the Service.</li>
              <li>Interfere with or disrupt the Service or its infrastructure.</li>
              <li>Scrape, copy, or redistribute content generated by the Service for commercial resale.</li>
              <li>Use automated tools to excessively access the Service beyond normal usage patterns.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">5. AI-Generated Content</h2>
            <p className="text-muted-foreground">
              The strategies, recommendations, and content generated by GTM Champion are produced by 
              artificial intelligence and should be used as guidance only. While we strive for accuracy 
              and relevance, AI-generated content may contain errors or may not be suitable for every 
              business context. You are responsible for reviewing and adapting any recommendations 
              before implementing them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">6. Intellectual Property</h2>
            <p className="text-muted-foreground">
              You retain ownership of any content you submit to the Service (such as your website URL). 
              You grant us a limited license to process this content for the purpose of providing the Service. 
              The GTM Champion platform, including its design, features, and underlying technology, 
              remains our intellectual property.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">7. Subscriptions and Payments</h2>
            <p className="text-muted-foreground">
              Some features may require a paid subscription. Payments are processed by Stripe. 
              Subscription terms, pricing, and billing cycles are displayed at the time of purchase. 
              You may cancel your subscription at any time through your account settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">8. Limitation of Liability</h2>
            <p className="text-muted-foreground">
              The Service is provided "as is" without warranties of any kind. We are not liable for 
              any indirect, incidental, or consequential damages arising from your use of the Service. 
              Our total liability shall not exceed the amount you paid for the Service in the 
              preceding 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">9. Termination</h2>
            <p className="text-muted-foreground">
              We reserve the right to suspend or terminate your account if you violate these terms. 
              You may delete your account at any time, which will permanently remove all your data 
              from our systems.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">10. Changes to Terms</h2>
            <p className="text-muted-foreground">
              We may modify these terms at any time. Continued use of the Service after changes 
              constitutes acceptance of the updated terms. We will notify you of material changes 
              via email or platform notification.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-semibold mb-3">11. Contact</h2>
            <p className="text-muted-foreground">
              For questions about these terms, please visit our{" "}
              <Link href="/contact" className="text-primary hover:underline">contact page</Link>.
            </p>
          </section>
        </div>
      </main>

      <footer className="bg-slate-900 text-slate-300 py-8" role="contentinfo">
        <div className="container mx-auto px-4 md:px-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-sm text-slate-400">© {new Date().getFullYear()} GTM Champion. All rights reserved.</p>
          <div className="flex gap-6 text-sm">
            <Link href="/about" className="hover:text-white transition-colors">About</Link>
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
